name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set image tag from release tag
      run: echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag miziper/dac_web:${{ env.IMAGE_TAG }}

    - name: Push Docker image
      run: docker push miziper/dac_web:${{ env.IMAGE_TAG }}
